--- #YAML:1.0
name:                Net-Packet-Shell
version:             0.21
abstract:            Scapy like implementation using Net::Packet, just to prove it
license:             Artistic
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Net::Packet:                   3.20
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - GomoR <perl@gomor.org>
